### ISSUE TITLE
changes in counters in SQL 2012

### ISSUE THREAD

**Issue by zitzman** [NagiosEnterprises/check_mssql_collection#10]
counters like totalpages not longer relevant

https://blogs.msdn.microsoft.com/sqlosteam/2012/07/11/memory-manager-surface-area-changes-in-sql-server-2012/

**Comment by hedenface** [comment]
Honestly, unsure if bug or enhancement at this point. I hate to say this, but this project obviously hasn't gotten a lot of love. We're trying to change that now, so I'm going to try and get back to this very soon. No promises on an actual timeframe though :)

**Comment by hedenface** [comment]
@Madlohe This one too. It would be nice to get it up to date. If not, no worries.

**Comment by Madlohe** [comment]
Yes, I can look into this.

**Comment by box293** [comment]
I can also report some issues when testing against SQL 2016 with `--stolenpages` and `--freepages`:

```
/usr/local/nagios/libexec/check_mssql_server.py -H mssql01.box293.local -U 'nagios' -P 'xxxxx' -p 14333 --stolenpages --warning 500 --critical 700

Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 469, in <module>
    main()
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 435, in main
    execute_query(mssql, options, host)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 448, in execute_query
    mssql_query.do(mssql)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 284, in do
    self.run_on_connection(connection)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 271, in run_on_connection
    self.query_result = cur.fetchone()[0]
TypeError: 'NoneType' object is unsubscriptable

/usr/local/nagios/libexec/check_mssql_server.py -H mssql01.box293.local -U 'nagios' -P 'xxxxx' -p 14333 --freepages --warning 10 --critical 20

Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 469, in <module>
    main()
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 435, in main
    execute_query(mssql, options, host)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 448, in execute_query
    mssql_query.do(mssql)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 284, in do
    self.run_on_connection(connection)
  File "/usr/local/nagios/libexec/check_mssql_server.py", line 271, in run_on_connection
    self.query_result = cur.fetchone()[0]
TypeError: 'NoneType' object is unsubscriptable
```

I assume these are related.

**Comment by jomann09** [comment]
Updating this with another link https://blogs.msdn.microsoft.com/vsanil/2012/11/21/did-some-performance-counters-like-free-pages-disappear-in-sql-2012/

This will be updated with a new plugin that will be part of the collection, older versions of SQL server will be told to use the old plugins, old plugins running against new server will be told to use new plugins etc
